### ISSUE TITLE
I am facing the same issue. Have anyone fixed it?

### ISSUE THREAD

**Issue by Reshmiramesh** [Issam28/Brain-tumor-segmentation#19]
I am facing the same issue. Have anyone fixed it? 

Using TensorFlow backend.
Traceback (most recent call last):
  File "extract_patches.py", line 236, in <module>
    Patches,Y_labels=pipe.sample_patches_randomly(num_patches,d, h, w)
  File "extract_patches.py", line 74, in sample_patches_randomly
    gt_im = np.swapaxes(self.train_im, 0, 1)[4]   
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 585, in swapaxes
    return _wrapfunc(a, 'swapaxes', axis1, axis2)
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
numpy.AxisError: axis2: axis 1 is out of bounds for array of dimension 1

**Comment by lucianigithub** [comment]
you solved? I have the same issue
