### ISSUE TITLE
ValueError: bad axis2 argument to swapaxes

### ISSUE THREAD

**Issue by sara-kassani** [Issam28/Brain-tumor-segmentation#2]
In line 74 (gt_im = np.swapaxes(self.train_im, 0, 1)[4]) at extract_patches.py I will get the following error.
ValueError: bad axis2 argument to swapaxes.

**Comment by Issam28** [comment]
Are you using Brats2017 datasets ? which numpy version do you use?

**Comment by sara-kassani** [comment]
I'm using brats 2017 and my numpy version is 1.14.2.

**Comment by ritwik12** [comment]
I am also getting the same error

**Comment by sara-kassani** [comment]
I've run the code on google colab and the problem was solved. I guess the error caused because of memory error.

**Comment by Issam28** [comment]
yes it's probably because of memory we you transform numpy arrays to np.float you'll quickly run out of memory , i've done this project on a machine that has 64 GO of RAM and i've tested it on google colab which has 13GO of ram and it worked

**Comment by ritwik12** [comment]
@sara-kassani I have never used colab. Can you guide me how to use this project for colab? if it's not a long procedure for you to explain.

**Comment by sara-kassani** [comment]
@ritwik12 It's not easy to work with google colab. I've also worked with http://floydhub.com/ and http://paperspace.com/. I recommend you paperspace.

**Comment by ritwik12** [comment]
@sara-kassani  ohk, thanks a lot for your help.

**Comment by agungfathur** [comment]
i try the program, but still error in line 74 with same error. i already try it on google colabs. any solutions?

**Comment by Issam28** [comment]
@agungfathur check the filepath of the dataset

**Comment by TigabuYaya** [comment]
Please could you provide me the output?

**Comment by TigabuYaya** [comment]
Dear Isam, When I tried to run the source code on google colab, I got his error. can I you help me please
!python extract_patches.py
Using TensorFlow backend.
iteration [0]
iteration [10]
tcmalloc: large alloc 1704345600 bytes == 0x6b68a000 @  0x7f9cb35d61e7 0x7f9cb0ccda41 0x7f9cb0d30c13 0x7f9cb0d340c4 0x7f9cb0d34605 0x7f9cb0dcb201 0x511b75 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x51057e 0x5917a1 0x574e90 0x5264b1 0x59f9fc 0x511b0a 0x4f6070 0x4f3338 0x4f4ab3 0x640862 0x64091a 0x6429e0 0x634117 0x4b6e80 0x7f9cb31d3b97 0x5bf75a
tcmalloc: large alloc 2296381440 bytes == 0xd0fee000 @  0x7f9cb35d61e7 0x7f9cb0ccda41 0x7f9cb0d30c13 0x7f9cb0d340c4 0x7f9cb0d34605 0x7f9cb0dcb201 0x511b75 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x4f4ab3 0x640862 0x64091a 0x6429e0 0x634117 0x4b6e80 0x7f9cb31d3b97 0x5bf75a
tcmalloc: large alloc 2296381440 bytes == 0x159dee000 @  0x7f9cb35d61e7 0x7f9cb0ccda41 0x7f9cb0d30c13 0x7f9cb0d332ec 0x7f9cb0dc4f02 0x511b75 0x4f5277 0x4f3338 0x4f4ab3 0x640862 0x64091a 0x6429e0 0x634117 0x4b6e80 0x7f9cb31d3b97 0x5bf75a
tcmalloc: large alloc 2296381440 bytes == 0xd0fee000 @  0x7f9cb35d8001 0x7f9cb0ccdb85 0x7f9cb0d30b43 0x7f9cb0d32a86 0x7f9cb0dca868 0x511b75 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x4f4ab3 0x640862 0x64091a 0x6429e0 0x634117 0x4b6e80 0x7f9cb31d3b97 0x5bf75a
tcmalloc: large alloc 2296381440 bytes == 0xd0fee000 @  0x7f9cb35d61e7 0x7f9cb0ccda41 0x7f9cb0d30c13 0x7f9cb0d340c4 0x7f9cb0d34605 0x7f9cb0dcb201 0x511b75 0x4f5277 0x4f3338 0x4f4ab3 0x640862 0x64091a 0x6429e0 0x634117 0x4b6e80 0x7f9cb31d3b97 0x5bf75a
Size of the patches :  (8760, 128, 128, 4)
Size of their correponding targets :  (8760, 128, 128, 4)

!python train.py
Using TensorFlow backend.
/content/drive/My Drive/model.py:34: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("ac...)`
  model = Model(input=i, output=out)
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    brain_seg = Training(batch_size=4,nb_epoch=3,load_model_resume_training=model_to_load)
  File "train.py", line 42, in __init__
    unet =Unet_model(img_shape=(128,128,4))
  File "/content/drive/My Drive/model.py", line 21, in __init__
    self.model =self.compile_unet()
  File "/content/drive/My Drive/model.py", line 37, in compile_unet
    model.compile(loss=gen_dice_loss, optimizer=sgd, metrics=[dice_whole_metric,dice_core_metric,dice_en_metric])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 936, in compile
    handle_metrics(output_metrics)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 914, in handle_metrics
    mask=masks[i])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 429, in weighted
    score_array = fn(y_true, y_pred)
  File "/content/drive/My Drive/losses.py", line 47, in dice_core_metric
    y_core=K.sum(y_true_f[:,[1,3]],axis=1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 491, in _slice_helper
    end.append(s + 1)
TypeError: can only concatenate list (not "int") to list

**Comment by TigabuYaya** [comment]
> In line 74 (gt_im = np.swapaxes(self.train_im, 0, 1)[4]) at extract_patches.py I will get the following error.
> ValueError: bad axis2 argument to swapaxes.

This is because your file paths,  @ line 216 and 217 ( path_HGG = glob('Brats2017/Brats17TrainingData/HGG/**')
    path_LGG = glob('Brats2017/Brats17TrainingData/LGG/**')), are not correctly specified.

**Comment by takrouni** [comment]
Good morning,
Please, i need urgently the Brats2017 dataset 
Thank you.

**Comment by TigabuYaya** [comment]
> 
> 
> Good morning,
> Please, i need urgently the Brats2017 dataset
> Thank you.

your email, please.

**Comment by Mickind** [comment]
Hello everyone,
How can I find the Brats2017 dataset? I think, without it, I can not execute extract_patches.py.
@TigabuYaya Could you please kindly pass me by email?
My e-mail: crtmiky@gmail.com

**Comment by takrouni** [comment]
Hello,
Same problem :(

**Comment by Issam28** [comment]
for everyone's asking for BraTS 2017 or BraTS 2018 datasets you can request them via this website : [https://ipp.cbica.upenn.edu/](url)

**Comment by vaibhavshukla182** [comment]
> > Good morning,
> > Please, i need urgently the Brats2017 dataset
> > Thank you.
> 
> your email, please.

vaibhavshukla182@gmail.com
Its urgent

**Comment by Wonkun-Chen** [comment]
Hello, is there anybody could send me a BraTS2017 datasets please? when I wrote an email to cbica ask for the datasets, they say they don`t provide this datasets, only the latest one, so i`m here search for it. who can send it to my email(15689432890@163.com)? please!!!

**Comment by TigabuYaya** [comment]
I hv z dataset

**Comment by cqlouis** [comment]
> > In line 74 (gt_im = np.swapaxes(self.train_im, 0, 1)[4]) at extract_patches.py I will get the following error.
> > ValueError: bad axis2 argument to swapaxes.
> 
> This is because your file paths, @ line 216 and 217 ( path_HGG = glob('Brats2017/Brats17TrainingData/HGG/**') path_LGG = glob('Brats2017/Brats17TrainingData/LGG/**')), are not correctly specified.

yes!
I met the same problem, after I changed the path to absolute path , it worked!
