### ISSUE TITLE
ValueError: Cannot create group in read only mode.

### ISSUE THREAD

**Issue by Nareshchary** [Issam28/Brain-tumor-segmentation#6]
Using TensorFlow backend.
Traceback (most recent call last):
  File "/content/drive/My Drive/Brain-tumor-segmentation-master/train.py", line 108, in <module>
    brain_seg = Training(batch_size=4,nb_epoch=3,load_model_resume_training=model_to_load)
  File "/content/drive/My Drive/Brain-tumor-segmentation-master/train.py", line 39, in __init__
    self.model =load_model(load_model_resume_training,custom_objects={'gen_dice_loss': gen_dice_loss,'dice_whole_metric':dice_whole_metric,'dice_core_metric':dice_core_metric,'dice_en_metric':dice_en_metric})
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

while running train.py in colab got this error.

**Comment by sapnii2** [comment]
You got any solution for ValueError? I am with same error please help.
Thanks

**Comment by latestgo** [comment]
I got any solution for ValueError.
If you want to train the model from scratch, the parameter `load_model_resume_training` shoud be `None`.
If you train the model from the pretrained weights provided by @Issam28, the parameter `load_model_resume_training` shoud be pretrained weights filepath without extension and code
```python
self.model =load_model(load_model_resume_training,custom_objects={'gen_dice_loss': gen_dice_loss,'dice_whole_metric':dice_whole_metric,'dice_core_metric':dice_core_metric,'dice_en_metric':dice_en_metric})
```
change to 
```python
self.model = self.load_model(load_model_resume_training)
sgd = SGD(lr=0.08, momentum=0.9, decay=5e-6, nesterov=False)
self.model.compile(loss=gen_dice_loss, optimizer=sgd, metrics=[dice_whole_metric,dice_core_metric,dice_en_metric])
```

**Comment by latestgo** [comment]
> > I got any solution for ValueError.
> > If you want to train the model from scratch, the parameter `load_model_resume_training` shoud be `None`.
> > If you train the model from the pretrained weights provided by @Issam28, the parameter `load_model_resume_training` shoud be pretrained weights filepath without extension and code
> > ```python
> > self.model =load_model(load_model_resume_training,custom_objects={'gen_dice_loss': gen_dice_loss,'dice_whole_metric':dice_whole_metric,'dice_core_metric':dice_core_metric,'dice_en_metric':dice_en_metric})
> > ```
> > 
> > 
> > change to
> > ```python
> > self.model = self.load_model(load_model_resume_training)
> > sgd = SGD(lr=0.08, momentum=0.9, decay=5e-6, nesterov=False)
> > self.model.compile(loss=gen_dice_loss, optimizer=sgd, metrics=[dice_whole_metric,dice_core_metric,dice_en_metric])
> > ```
> 
> The load_model function needs '{ }.json', but I didn't find it

Hello, hope it's not too late.
The json file can be produced by function save_model in object Train.

**Comment by qiuyuan666** [comment]
Hello, I used your solution(change self.model) and ran into this problem as well:No such file or directory: '*******/pretrained_weights/ResUnet.epoch_02.hdf5.json'
I don't understand you said "The json file can be produced by function save_model in object Train.", Can you elaborate a bit more on how to solve this problem?
Thank you very much! I am looking forward to your reply.
